INSERT INTO t_e_film_flm(flm_titre, flm_resume, flm_datesortie, flm_duree, flm_genre)
VALUES ('Avengers : L''ère d''Ultron', 'Alors que Tony Stark tente de relancer un programme de maintien de la paix jusque-là suspendu, les choses tournent mal et les super-héros Iron Man, Captain America, Thor, Hulk, Black Widow et Hawkeye vont devoir à nouveau unir leurs forces pour combattre le plus puissant de leurs adversaires : le terrible Ultron, un être technologique terrifiant qui s''est juré d''éradiquer l''espèce humaine.', '30/09/2015', 120, 'Fantastique');
INSERT INTO t_e_film_flm(flm_titre, flm_resume, flm_datesortie, flm_duree, flm_genre)
VALUES ('Lucy', 'A la suite de circonstances indépendantes de sa volonté, une jeune étudiante voit ses capacités intellectuelles se développer à l''infini. Elle colonise son cerveau, et acquiert des pouvoirs illimités.', '06/12/2014', 90, 'Science-fiction');
INSERT INTO t_e_film_flm(flm_titre, flm_resume, flm_datesortie, flm_duree, flm_genre)
VALUES ('Virgin suicides', null, '10/07/2011', 90, 'Drame');

INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Calida', 'Lilley', '0653930778', 'clilleymd@last.fm', 'Toto12345678!', 'Impasse des bergeronnettes', '74200', 'Allinges', 'France', 46.344795, 6.4885845);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Gwendolin', 'Dominguez', '0724970555', 'gdominguez0@washingtonpost.com', 'Toto12345678!', 'Chemin de gom', '73420', 'Voglans', 'France', 45.622154, 5.8853216);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Randolph', 'Richings', '0630271158', 'rrichings1@naver.com', 'Toto12345678!', 'Route des charmottes d''en bas', '74890', 'Bons-en-Chablais', 'France', 46.25732, 6.367676);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Aymer', 'Bramford', '0637880069', 'abramford2@businesswire.com', 'Toto12345678!', 'Route du plateau', '73340', 'Lescheraines', 'France', 45.713882, 6.107125);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Leroy', 'Rudland', '0763430545', 'lrudland3@360.cn', 'Toto12345678!', 'Route des tavernettes', '74370', 'Charvonnex', 'France', 45.98477, 6.1659126);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Fancy', 'Ransbury', '0678166372', 'fransbury4@jimdo.com', 'Toto12345678!', 'Route de chez gaillard', '74330', 'Mésigny', 'France', 45.984097, 5.997723);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Baxy', 'Jeger', '0632012488', 'bjeger5@edublogs.org', 'Toto12345678!', 'Impasse de la gravelière', '74890', 'Lully', 'France', 46.287777, 6.417852);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Pier', 'Handscomb', '0733836680', 'phandscomb6@netlog.com', 'Toto12345678!', 'Route du champ de l''ale', '74650', 'Chavanod', 'France', 45.87795, 6.0602098);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Dre', 'Wride', '0718042611', 'dwride7@hexun.com', 'Toto12345678!', 'Route du sapenay', '73310', 'Chindrieux', 'France', 45.83013, 5.851562);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Martie', 'Greeson', '0628404307', 'mgreeson8@amazon.com', 'Toto12345678!', 'Rue du chef lieu', '73630', 'La Compôte', 'France', 45.67057, 6.1603208);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Stevie', 'Romaine', '0754859713', 'sromaine9@devhub.com', 'Toto12345678!', 'Chemin de matti', '74100', 'Vétraz-Monthoux', 'France', 46.17579, 6.2480574);
INSERT INTO t_e_utilisateur_utl (utl_nom, utl_prenom, utl_mobile, utl_mail, utl_pwd, utl_rue, utl_cp, utl_ville, utl_pays, utl_latitude, utl_longitude) VALUES ('Kikelia', 'Bome', '0603470194', 'kbomea@networksolutions.com', 'Toto12345678!', 'Piste pastorale du follière', '74360', 'La Chapelle-d''Abondance', 'France', 46.27805, 6.779475);

INSERT INTO t_j_notation_not(utl_id,flm_id,not_note) VALUES (1,1,5);
INSERT INTO t_j_notation_not(utl_id,flm_id,not_note) VALUES (3,1,3);
INSERT INTO t_j_notation_not(utl_id,flm_id,not_note) VALUES (5,1,3);
INSERT INTO t_j_notation_not(utl_id,flm_id,not_note) VALUES (10,1,1);
INSERT INTO t_j_notation_not(utl_id,flm_id,not_note) VALUES (12,1,0);
